screen_config/config_app/urls.py
from django.conf.urls import re_path
from config_app import views

app_name = 'config_app'

urlpatterns = [
    re_path(r'^new_screen/$', views.new_screen,name='new_screen'),
    re_path(r'^new_panel/$', views.new_panel,name='new_panel'),
]

screen_config/screen_config/urls.py
from django.contrib import admin
from django.urls import path, re_path
from config_app import views
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', views.index, name="index"),
    re_path(r'^config_app/', include('config_app.urls')),
]

screen_config/config_app/models.py
from django.db import models

# Create your models here.

class LedPanel(models.Model):
    panel_name = models.CharField(max_length=264, unique=True)
    panel_width = models.IntegerField()
    panel_height = models.IntegerField()
    panel_pixel_width = models.IntegerField()
    panel_pixel_height = models.IntegerField()
    panel_curent_draw = models.IntegerField()

    def __str__(self):
        return self.panel_name

    def panel_resolution(self):
        return self.panel_pixel_width * self.panel_pixel_height

class Screen(models.Model):
    screen_name = models.CharField(max_length=264, unique=True)
    panel = models.ForeignKey(LedPanel, on_delete = models.CASCADE)
    panels_wide = models.IntegerField()
    panels_high = models.IntegerField()
    refresh_rate = models.IntegerField()

    def __str__(self):
        return str(self.screen_name)

    @ property
    def screen_resolution(self):
        return (self.panel.panel_pixel_width * self.panels_wide, self.panel.panel_pixel_height * self.panels_high)

    @ property
    def screen_width(self):
        return str((self.panel.panel_width * self.panels_wide) / 1000) + "m"

    @ property
    def screen_height(self):
        return str((self.panel.panel_height * self.panels_high) / 1000) + "m"

    @ property
    def panels_per_string(self):
        if self.refresh_rate == 60:
            return 552960 / self.panel.panel_resolution()
        else:
            print("I'm sorry, this refresh rate is not supported by this applicaiton yet!")

screen_config/config_app/forms.py
from django import forms
from django.core import validators
from config_app.models import LedPanel, Screen

class NewPanelForm(forms.ModelForm):
    class Meta():
        model = LedPanel
        fields = ("panel_name", "panel_width", "panel_height", "panel_pixel_width", "panel_pixel_height", "panel_curent_draw")


class NewScreenForm(forms.ModelForm):
    class Meta():
        model = Screen
        fields = ("screen_name","panel","panels_wide","panels_high","refresh_rate")

screen_config/config_app/views.py
from django.shortcuts import render
from config_app.forms import NewPanelForm, NewScreenForm
from config_app.models import Screen

# Create your views here.
def index(request):
    screens_list = Screen.objects.order_by('screen_name')
    screen_dict = {'screens_list': screens_list}
    return render(request,'config_app/index.html', context=screen_dict)


def new_panel(request):
    registered = False
    if request.method == "POST":
        new_panel_form = NewPanelForm(data=request.POST)

        if new_panel_form.is_valid():

            panel = new_panel_form.save()

            registered = True

        else:
            print(new_panel_form.errors)

    else:
        new_panel_form = NewPanelForm()

    return render(request,'config_app/new_panel.html',
                            {'new_panel_form':new_panel_form,
                                'registered':registered})

def new_screen(request):
    registered = False
    if request.method == "POST":
        new_screen_form = NewScreenForm(data=request.POST)

        if new_screen_form.is_valid():

            screen = new_screen_form.save()

            registered = True

        else:
            print(new_screen_form.errors)

    else:
        new_screen_form = NewScreenForm()

    return render(request,'config_app/new_screen.html',
                            {'new_screen_form':new_screen_form,
                                'registered':registered})

screen_config/templates/config_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Screen Config App</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "/css/master.css" %}">
  </head>
  <body>
    <nav class='navbar navbar-default navbar-static-top'>
      <div class="container">
        <ul class="nav nabar-nav">
          <li><a class="navbar-link" href="{% url 'index' %}">The LED Shed</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'config_app:new_panel' %}">Register New Panel</a></li>
          <li><a class="navbar-link" href="{% url 'config_app:new_screen' %}">Register New Screen</a></li>
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>

  </body>
</html>

screen_config/templates/config_app/index.html
{% extends "config_app/base.html" %}
{% block body_block %}
<div class="jumbotron">
  <h1>Screen Config App</h1>
  {% if screens_list %}
    <table>
      <thead>
        <td>Screen name</td>
        <td>Panel</td>
        <td>Screen Width</td>
        <td>Screen Height</td>
        <td>Refresh Rate</td>
        <td>Panel Resolution</td>
      </thead>
      {% for screen in screens_list %}
      <tr>
        <td>{{screen.screen_name}}</td>
        <td>{{screen.panel}}</td>
        <td>{{screen.screen_width}}</td>
        <td>{{screen.screen_height}}</td>
        <td>{{screen.refresh_rate}}</td>
        <td>{{screen.screen_resolution}}</td>
      </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>NO ACCESS RECORDS FOUND</p>
  {% endif %}
</div>

{% endblock %}

screen_config/templates/config_app/new_panel.html
{% extends "config_app/base.html" %}
{% load static %}
{% block body_block %}

<div class="jumbotron">

  {% if registered %}
    <h1>Thank You For Registering a New Panel!</h1>
  {% else %}
    <h1>Register Here!</h1>
    <h3>Fill Out the Form!</h3>
    <form enctype="multipart/form-data" method="post" >
      {% csrf_token %}
      {{ new_panel_form.as_p }}
      <input type="submit" name="" value="Register">
    </form>
  {% endif %}

</div>

{% endblock %}

screen_config/templates/config_app/new_screen.html
{% extends "config_app/base.html" %}
{% load static %}
{% block body_block %}

<div class="jumbotron">

  {% if registered %}
    <h1>Thank You For Registering a New Screen!</h1>
  {% else %}
    <h1>Please Enter New Panel Details</h1>
    <h3>Fill Out the Form!</h3>
    <form enctype="multipart/form-data" method="post" >
      {% csrf_token %}
      {{ new_screen_form.as_p }}
      <input type="submit" name="" value="Register">
    </form>
  {% endif %}

</div>

{% endblock %}